/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_denuarchirinos;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Denuar
 */
public class Ventana extends javax.swing.JFrame {
    Usuario user;
    Artista artist;
    ArrayList <Usuario> usuarios = new ArrayList();
    ArrayList <Artista> artistas = new ArrayList();
    String nombre, apellido, usuario, contraseña, genero;
    Date fecha;
    Cancion cancion;
    ArrayList <Cancion> canciones = new ArrayList();
    Album album;
    int duracion=0, estadoLogU=0, estadoLogA=0, userLogeado=0, artistLogeado=0;
    String nombreC, nombreA, nombreAlbum;
    AdministrarBarra ab;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        jMenu3.setEnabled(false);
        jMenu4.setEnabled(false);
        
//        HiloHora h = new HiloHora(jl_hora);
//        Thread proceso1 = new Thread(h);
//        proceso1.start();
        
        ab = new AdministrarBarra(pb1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_signUser = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JTextField();
        dc_fechaN = new rojeru_san.componentes.RSDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jd_logUser = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_logUser = new javax.swing.JTextField();
        txt_logPass = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        jd_BaseUsuarios = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cb_usuarios = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jd_signArtist = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_guardar1 = new javax.swing.JButton();
        txt_nombre1 = new javax.swing.JTextField();
        txt_apellido1 = new javax.swing.JTextField();
        txt_usuario1 = new javax.swing.JTextField();
        txt_contraseña1 = new javax.swing.JTextField();
        dc_fechaN1 = new rojeru_san.componentes.RSDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jd_logArtist = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_logUser1 = new javax.swing.JTextField();
        txt_logPass1 = new javax.swing.JTextField();
        btn_aceptar1 = new javax.swing.JButton();
        jd_seguirArtista = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        btn_seguir = new javax.swing.JButton();
        cb_artistas = new javax.swing.JComboBox<>();
        jd_verSeguidores = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        cb_seguidores = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txt_artistActual = new javax.swing.JTextField();
        jd_agregarCanciones = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btn_guardarCancion = new javax.swing.JButton();
        txt_nCancion = new javax.swing.JTextField();
        txt_duracion = new javax.swing.JTextField();
        txt_nArtista = new javax.swing.JTextField();
        dc1 = new rojeru_san.componentes.RSDateChooser();
        jLabel28 = new javax.swing.JLabel();
        cb_albunes = new javax.swing.JComboBox<>();
        Reproductor = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        pb1 = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        cb_todasCanciones = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jd_agregarAlbum = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btn_guardarAlbum = new javax.swing.JButton();
        txt_nAlbum = new javax.swing.JTextField();
        txt_cancionAlbum = new javax.swing.JTextField();
        txt_artAlbum = new javax.swing.JTextField();
        dc2 = new rojeru_san.componentes.RSDateChooser();
        jLabel33 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm3 = new javax.swing.JMenuItem();
        jm4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jm1 = new javax.swing.JMenuItem();
        jm2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        jd_signUser.setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Usuario");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Fecha Nacimiento");

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel6.setText("Registro Usuarios");

        javax.swing.GroupLayout jd_signUserLayout = new javax.swing.GroupLayout(jd_signUser.getContentPane());
        jd_signUser.getContentPane().setLayout(jd_signUserLayout);
        jd_signUserLayout.setHorizontalGroup(
            jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUserLayout.createSequentialGroup()
                .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signUserLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(71, 71, 71)
                        .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_fechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_signUserLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btn_guardar))
                    .addGroup(jd_signUserLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel6)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jd_signUserLayout.setVerticalGroup(
            jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_signUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signUserLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5))
                    .addGroup(jd_signUserLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(dc_fechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(btn_guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_logUser.setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel14.setText("Usuario");

        jLabel15.setText("Contraseña");

        jLabel16.setText("Log In Usuarios");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_logUserLayout = new javax.swing.GroupLayout(jd_logUser.getContentPane());
        jd_logUser.getContentPane().setLayout(jd_logUserLayout);
        jd_logUserLayout.setHorizontalGroup(
            jd_logUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_logUserLayout.createSequentialGroup()
                .addGroup(jd_logUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_logUserLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jd_logUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(68, 68, 68)
                        .addGroup(jd_logUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_logPass, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_logUser, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_logUserLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel16))
                    .addGroup(jd_logUserLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btn_aceptar)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jd_logUserLayout.setVerticalGroup(
            jd_logUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_logUserLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel16)
                .addGap(33, 33, 33)
                .addGroup(jd_logUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_logUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_logUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_logPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btn_aceptar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Usuarios");

        cb_usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_usuariosItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout jd_BaseUsuariosLayout = new javax.swing.GroupLayout(jd_BaseUsuarios.getContentPane());
        jd_BaseUsuarios.getContentPane().setLayout(jd_BaseUsuariosLayout);
        jd_BaseUsuariosLayout.setHorizontalGroup(
            jd_BaseUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jd_BaseUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_BaseUsuariosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jd_BaseUsuariosLayout.setVerticalGroup(
            jd_BaseUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
            .addGroup(jd_BaseUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_BaseUsuariosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jd_signArtist.setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel7.setText("Nombre");

        jLabel9.setText("Apellido");

        jLabel10.setText("Usuario");

        jLabel11.setText("Contraseña");

        jLabel12.setText("Fecha Nacimiento");

        btn_guardar1.setText("Guardar");
        btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Registro Artistas");

        javax.swing.GroupLayout jd_signArtistLayout = new javax.swing.GroupLayout(jd_signArtist.getContentPane());
        jd_signArtist.getContentPane().setLayout(jd_signArtistLayout);
        jd_signArtistLayout.setHorizontalGroup(
            jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signArtistLayout.createSequentialGroup()
                .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signArtistLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(71, 71, 71)
                        .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_fechaN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_signArtistLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btn_guardar1))
                    .addGroup(jd_signArtistLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel13)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jd_signArtistLayout.setVerticalGroup(
            jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signArtistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txt_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_signArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signArtistLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel12))
                    .addGroup(jd_signArtistLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(dc_fechaN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(btn_guardar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_logArtist.setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel17.setText("Usuario");

        jLabel18.setText("Contraseña");

        jLabel19.setText("Log In Artistas");

        btn_aceptar1.setText("Aceptar");
        btn_aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_logArtistLayout = new javax.swing.GroupLayout(jd_logArtist.getContentPane());
        jd_logArtist.getContentPane().setLayout(jd_logArtistLayout);
        jd_logArtistLayout.setHorizontalGroup(
            jd_logArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_logArtistLayout.createSequentialGroup()
                .addGroup(jd_logArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_logArtistLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jd_logArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(68, 68, 68)
                        .addGroup(jd_logArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_logPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_logUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_logArtistLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel19))
                    .addGroup(jd_logArtistLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btn_aceptar1)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jd_logArtistLayout.setVerticalGroup(
            jd_logArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_logArtistLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel19)
                .addGap(33, 33, 33)
                .addGroup(jd_logArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_logUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_logArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_logPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btn_aceptar1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jd_seguirArtista.setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel20.setText("Seleccionar Artista a seguir");

        btn_seguir.setText("Seguir");
        btn_seguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_seguirArtistaLayout = new javax.swing.GroupLayout(jd_seguirArtista.getContentPane());
        jd_seguirArtista.getContentPane().setLayout(jd_seguirArtistaLayout);
        jd_seguirArtistaLayout.setHorizontalGroup(
            jd_seguirArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_seguirArtistaLayout.createSequentialGroup()
                .addGroup(jd_seguirArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_seguirArtistaLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btn_seguir))
                    .addGroup(jd_seguirArtistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGap(28, 28, 28)
                        .addComponent(cb_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jd_seguirArtistaLayout.setVerticalGroup(
            jd_seguirArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_seguirArtistaLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jd_seguirArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cb_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btn_seguir)
                .addGap(105, 105, 105))
        );

        jd_verSeguidores.setMinimumSize(new java.awt.Dimension(600, 500));

        jLabel21.setText("Seguidores");

        jLabel22.setText("Artista Actual:");

        javax.swing.GroupLayout jd_verSeguidoresLayout = new javax.swing.GroupLayout(jd_verSeguidores.getContentPane());
        jd_verSeguidores.getContentPane().setLayout(jd_verSeguidoresLayout);
        jd_verSeguidoresLayout.setHorizontalGroup(
            jd_verSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_verSeguidoresLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jd_verSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_verSeguidoresLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_artistActual, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_verSeguidoresLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(cb_seguidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jd_verSeguidoresLayout.setVerticalGroup(
            jd_verSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_verSeguidoresLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jd_verSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_artistActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_verSeguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cb_seguidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jd_agregarCanciones.setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel23.setText("Agregar Canciones");

        jLabel24.setText("Nombre");

        jLabel25.setText("Artista");

        jLabel26.setText("Año");

        jLabel27.setText("Duracion (s)");

        btn_guardarCancion.setText("Guardar");
        btn_guardarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCancionActionPerformed(evt);
            }
        });

        jLabel28.setText("Album");

        javax.swing.GroupLayout jd_agregarCancionesLayout = new javax.swing.GroupLayout(jd_agregarCanciones.getContentPane());
        jd_agregarCanciones.getContentPane().setLayout(jd_agregarCancionesLayout);
        jd_agregarCancionesLayout.setHorizontalGroup(
            jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarCancionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardarCancion)
                .addGap(239, 239, 239))
            .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_nCancion)
                                                .addComponent(txt_nArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                            .addComponent(cb_albunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel28))))
                    .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel23)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jd_agregarCancionesLayout.setVerticalGroup(
            jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(13, 13, 13)
                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cb_albunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_nCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_nArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarCancionesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel26)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarCancionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(jd_agregarCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btn_guardarCancion)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Reproductor.setMinimumSize(new java.awt.Dimension(900, 700));

        jLabel34.setText("Reproductor");

        jLabel35.setText("Seleccionar Cancion");

        jToggleButton1.setText("Reproducir Cancion Actual");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Agregar A la lista de Reproduccion");

        pb1.setMaximum(100000000);
        pb1.setMinimumSize(new java.awt.Dimension(900, 600));

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane2.setViewportView(ta1);

        jLabel36.setText("Historial:");

        jLabel37.setText("Lista de reproduccion");

        jButton1.setText("Reproducir lista de Reproduccion");

        javax.swing.GroupLayout ReproductorLayout = new javax.swing.GroupLayout(Reproductor.getContentPane());
        Reproductor.getContentPane().setLayout(ReproductorLayout);
        ReproductorLayout.setHorizontalGroup(
            ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReproductorLayout.createSequentialGroup()
                .addGroup(ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ReproductorLayout.createSequentialGroup()
                        .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1))
                    .addGroup(ReproductorLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel34))
                    .addGroup(ReproductorLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReproductorLayout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(85, 85, 85)
                                .addComponent(jToggleButton2))
                            .addGroup(ReproductorLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(cb_todasCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel37)
                                .addGap(34, 34, 34)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(251, 251, 251))))
                    .addGroup(ReproductorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReproductorLayout.setVerticalGroup(
            ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReproductorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel34)
                .addGap(2, 2, 2)
                .addGroup(ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(cb_todasCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(42, 42, 42)
                .addGroup(ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addGroup(ReproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReproductorLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReproductorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25)))
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel29.setText("Album");

        jLabel30.setText("Artista");
        jLabel30.setMinimumSize(new java.awt.Dimension(700, 600));

        jLabel31.setText("año");

        jLabel32.setText("Canciones");

        btn_guardarAlbum.setText("Guardar");
        btn_guardarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarAlbumActionPerformed(evt);
            }
        });

        jLabel33.setText("Guardar Album");

        javax.swing.GroupLayout jd_agregarAlbumLayout = new javax.swing.GroupLayout(jd_agregarAlbum.getContentPane());
        jd_agregarAlbum.getContentPane().setLayout(jd_agregarAlbumLayout);
        jd_agregarAlbumLayout.setHorizontalGroup(
            jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarAlbumLayout.createSequentialGroup()
                .addGroup(jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarAlbumLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(38, 38, 38)
                        .addGroup(jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_artAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cancionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_agregarAlbumLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(btn_guardarAlbum))
                    .addGroup(jd_agregarAlbumLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel33)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jd_agregarAlbumLayout.setVerticalGroup(
            jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarAlbumLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel33)
                .addGap(29, 29, 29)
                .addGroup(jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_nAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_artAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarAlbumLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel31))
                    .addGroup(jd_agregarAlbumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jd_agregarAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_cancionAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_guardarAlbum)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Sign In");

        jm3.setText("Nuevo Usuario");
        jm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm3ActionPerformed(evt);
            }
        });
        jMenu1.add(jm3);

        jm4.setText("Nuevo Artista");
        jm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm4ActionPerformed(evt);
            }
        });
        jMenu1.add(jm4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Log In");

        jm1.setText("Usuario");
        jm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm1ActionPerformed(evt);
            }
        });
        jMenu2.add(jm1);

        jm2.setText("Artista");
        jm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm2ActionPerformed(evt);
            }
        });
        jMenu2.add(jm2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Usuarios");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Seguir Artista");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Crear PlayList");
        jMenu3.add(jMenuItem3);

        jMenuItem1.setText("Agregar Canciones a PlayList");
        jMenu3.add(jMenuItem1);

        jMenuItem7.setText("Reproductor");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Artistas");

        jMenuItem4.setText("Ver Seguidores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Agregar Albunes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Agregar Canciones");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Bases de datos");

        jMenuItem12.setText("Usuarios");
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("Artistas");
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        nombre = txt_nombre.getText();
        apellido = txt_apellido.getText();
        usuario = txt_usuario.getText();
        contraseña = txt_contraseña.getText();
        fecha = dc_fechaN.getDatoFecha();
        user = new Usuario(nombre, apellido, usuario, contraseña, fecha);
        usuarios.add(user);
        AdminUsuarios au = new AdminUsuarios ("./Usuarios.den");
        au.cargarArchivo();
        au.setUsuario(user);
        au.escribirArchivo();
        JOptionPane.showMessageDialog(this, "usuario guardado exitosamente");
        
        //reinicio de variables:
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_usuario.setText("");
        txt_contraseña.setText("");
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void cb_usuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_usuariosItemStateChanged
        // TODO add your handling code here:
//        if (evt.getStateChange() == 1) {
//            Usuario temp = (Usuario) cb_usuarios.getSelectedItem();
//            if (temp != null) {
//
//                jTable1.setModel(new javax.swing.table.DefaultTableModel(
//                    new Object [][] {
//
//                    },
//                    new String [] {
//                        "Descripcion", "U.V"
//                    }
//                ) {
//                    Class[] types = new Class [] {
//                        java.lang.String.class, java.lang.String.class
//                    };
//                    boolean[] canEdit = new boolean [] {
//                        false, false
//                    };
//
//                    public Class getColumnClass(int columnIndex) {
//                        return types [columnIndex];
//                    }
//
//                    public boolean isCellEditable(int rowIndex, int columnIndex) {
//                        return canEdit [columnIndex];
//                    }
//                });
//                for (int i = 0; i < temp.getCanciones().size(); i++) {
//                    Object row[] = {temp.getCanciones().get(i).getNombreCancion()};
//                    m.addRow(row);
//                    
//                }
//
//                for (Clase t : temp.getClases()) {
//                    Object row[]={t.getDescripcion(),t.getUv()  };
//                    DefaultTableModel m=(DefaultTableModel) jTable1.getModel();
//                    m.addRow(row);
//                    jTable1.setModel(m);
//                }
//            }
//        }
    }//GEN-LAST:event_cb_usuariosItemStateChanged

    private void btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar1ActionPerformed
        // TODO add your handling code here:
        System.out.println("");
        nombre = txt_nombre1.getText();
        apellido = txt_apellido1.getText();
        usuario = txt_usuario1.getText();
        contraseña = txt_contraseña1.getText();
        fecha = dc_fechaN1.getDatoFecha();
        artist = new Artista(nombre, apellido, usuario, contraseña, fecha);
        artistas.add(artist);
        AdminArtistas aa = new AdminArtistas ("./Artistas.den");
        aa.cargarArchivo();
        aa.setArtista(artist);
        aa.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Artista guardado exitosamente");
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_artistas.getModel();
        modelo.addElement(artist.getNombre());
        cb_artistas.setModel(modelo);
        
        //reinicio de variables:
        txt_nombre1.setText("");
        txt_apellido1.setText("");
        txt_usuario1.setText("");
        txt_contraseña1.setText("");
    }//GEN-LAST:event_btn_guardar1ActionPerformed

    private void jm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm3ActionPerformed
        // TODO add your handling code here:
        jd_signUser.setVisible(true);
    }//GEN-LAST:event_jm3ActionPerformed

    private void jm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm4ActionPerformed
        // TODO add your handling code here:
        jd_signArtist.setVisible(true);
    }//GEN-LAST:event_jm4ActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getUsuario().equals(txt_logUser.getText()) && usuarios.get(i).getContraseña().equals(txt_logPass.getText())){
                JOptionPane.showMessageDialog(this, "Bienvenido " + usuarios.get(i).getNombre());
                estadoLogU=1;
                userLogeado=i;
                jMenu3.setEnabled(true);
                jd_logUser.setVisible(false);
            }
        }
        if(estadoLogU==0){
            JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrecto");
        }
        
        //Reinicio de variables
        txt_logUser.setText("");
        txt_logPass.setText("");
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < artistas.size(); i++) {
            if (artistas.get(i).getUsuario().equals(txt_logUser1.getText()) && artistas.get(i).getContraseña().equals(txt_logPass1.getText())){
                JOptionPane.showMessageDialog(this, "Bienvenido " + artistas.get(i).getNombre());
                estadoLogA=1;
                artistLogeado=i;
                jMenu4.setEnabled(true);
                jd_logArtist.setVisible(false);
            }
        }
        if(estadoLogA==0){
            JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrecto");
        }
        
        //Reinicio de variables
        txt_logUser1.setText("");
        txt_logPass1.setText("");
    }//GEN-LAST:event_btn_aceptar1ActionPerformed

    private void jm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm1ActionPerformed
        // TODO add your handling code here:
        jd_logUser.setVisible(true);
    }//GEN-LAST:event_jm1ActionPerformed

    private void jm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm2ActionPerformed
        // TODO add your handling code here:
        jd_logArtist.setVisible(true);
    }//GEN-LAST:event_jm2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jd_verSeguidores.setVisible(true);
        txt_artistActual.setText(artistas.get(artistLogeado).getNombre());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:        
        if (estadoLogU==0){
            JOptionPane.showMessageDialog(this, "Debes iniciar secion primero");
        }
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jd_seguirArtista.setVisible(true);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel((Object[]) (Object) artistas);
        cb_artistas.setModel(modelo);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_seguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seguirActionPerformed
        // TODO add your handling code here:
        usuarios.get(userLogeado).setArtista(artistas.get(cb_artistas.getSelectedIndex()));//Agrego el artista seleccionado del comboBox al usuario que se ecuentra logeado actualmente
        JOptionPane.showMessageDialog(this, "Ahora sigues al Artista: " + artistas.get(cb_artistas.getSelectedIndex()).getNombre());
        
        artistas.get(cb_artistas.getSelectedIndex()).setSeguidor(usuarios.get(userLogeado));//Al artista seleccionado del comboBox le Agrego el Usuario que decide seguirlo como seguidor
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_seguidores.getModel();
        modelo.addElement(usuarios.get(userLogeado).getNombre());
        cb_artistas.setModel(modelo);
    }//GEN-LAST:event_btn_seguirActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jd_agregarCanciones.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btn_guardarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCancionActionPerformed
        // TODO add your handling code here:
        
        nombreC = txt_nCancion.getText();
        nombreA = txt_nArtista.getText();
        fecha=dc1.getDatoFecha();
        duracion = Integer.parseInt(txt_duracion.getText());
        cancion = new Cancion(nombreC, nombreA, fecha, duracion);
        artistas.get(artistLogeado).setAlbum(new Album("Sencillo", nombreA, fecha));//agrego la cancion al artista que se encuentra autenticado
        
        canciones.add(cancion);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_todasCanciones.getModel();
        modelo.addElement(cancion);
        cb_todasCanciones.setModel(modelo);
        //reinicio las variables
        txt_nCancion.setText("");
        txt_nArtista.setText("");
        txt_duracion.setText("");
    }//GEN-LAST:event_btn_guardarCancionActionPerformed

    private void btn_guardarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarAlbumActionPerformed
        // TODO add your handling code here:
        nombreAlbum = txt_nAlbum.getText();
        nombreA = txt_artAlbum.getText();
        fecha = dc2.getDatoFecha();
        album = new Album(nombreAlbum, nombreA, fecha);
        artistas.get(artistLogeado).setAlbum(album);
        
        canciones.add(new Cancion (txt_cancionAlbum.getText(), nombreA, fecha, duracion));
    }//GEN-LAST:event_btn_guardarAlbumActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jd_agregarAlbum.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        ab.start();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Reproductor.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Reproductor;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_aceptar1;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar1;
    private javax.swing.JButton btn_guardarAlbum;
    private javax.swing.JButton btn_guardarCancion;
    private javax.swing.JButton btn_seguir;
    private javax.swing.JComboBox<String> cb_albunes;
    private javax.swing.JComboBox<String> cb_artistas;
    private javax.swing.JComboBox<String> cb_seguidores;
    private javax.swing.JComboBox<String> cb_todasCanciones;
    private javax.swing.JComboBox cb_usuarios;
    private rojeru_san.componentes.RSDateChooser dc1;
    private rojeru_san.componentes.RSDateChooser dc2;
    private rojeru_san.componentes.RSDateChooser dc_fechaN;
    private rojeru_san.componentes.RSDateChooser dc_fechaN1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JDialog jd_BaseUsuarios;
    private javax.swing.JDialog jd_agregarAlbum;
    private javax.swing.JDialog jd_agregarCanciones;
    private javax.swing.JDialog jd_logArtist;
    private javax.swing.JDialog jd_logUser;
    private javax.swing.JDialog jd_seguirArtista;
    private javax.swing.JDialog jd_signArtist;
    private javax.swing.JDialog jd_signUser;
    private javax.swing.JDialog jd_verSeguidores;
    private javax.swing.JMenuItem jm1;
    private javax.swing.JMenuItem jm2;
    private javax.swing.JMenuItem jm3;
    private javax.swing.JMenuItem jm4;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_apellido1;
    private javax.swing.JTextField txt_artAlbum;
    private javax.swing.JTextField txt_artistActual;
    private javax.swing.JTextField txt_cancionAlbum;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_contraseña1;
    private javax.swing.JTextField txt_duracion;
    private javax.swing.JTextField txt_logPass;
    private javax.swing.JTextField txt_logPass1;
    private javax.swing.JTextField txt_logUser;
    private javax.swing.JTextField txt_logUser1;
    private javax.swing.JTextField txt_nAlbum;
    private javax.swing.JTextField txt_nArtista;
    private javax.swing.JTextField txt_nCancion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JTextField txt_usuario1;
    // End of variables declaration//GEN-END:variables
}
